### ISSUE TITLE
case class support

### ISSUE THREAD

**Issue by reibitto** [jatcwang/scalafix_use_named_param#1]
I tested this scalafix rule and it worked with methods and constructors, but not quite on case classes. Here's a minimal example:

```scala
case class Foo(a: Int, b: Int, c: Int)

Foo(1, 2, 3) // doesn't get transformed
new Foo(1, 2, 3) // works as expected: `new Foo(a = 1, b = 2, c = 3)`
Foo.apply(1, 2, 3) // `scala.MatchError: Foo.apply (of class scala.meta.Term$Select$TermSelectImpl)`
```

**Comment by jatcwang** [comment]
Thanks for the report. I have fixed the `apply` (and all method calls.... :zany_face: ) but case class should work (existing tests cover it).

**Comment by jatcwang** [comment]
@reibitto  Rubberducked myself when raising the issue in scalafix project.
To support case class (synthetic) apply methods you need this:

```
    scalacOptions ++= Seq(
      "-P:semanticdb:synthetics:on"
    )
```   

I added detection for this scalac option and will now fail with a nicer msg when it's missing
